name: CMake on multiple platforms

env:
  WORKSPACE: ${{ github.workspace }}/all
  BUILD_OUTPUT_DIR: ${{ github.workspace }}/all/build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Release ]
        c_compiler: [ gcc, clang, cl ]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: >
          cmake -B $BUILD_OUTPUT_DIR -S $WORKSPACE
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Build
        run: cmake --build $BUILD_OUTPUT_DIR --config ${{ matrix.build_type }}
      - name: Test
        working-directory: $BUILD_OUTPUT_DIR
        run: ctest --build-config ${{ matrix.build_type }}
