name: CMake on multiple platforms

env:
  WORKSPACE: ${{ github.workspace }}/all
  BUILD_OUTPUT_DIR: ${{ github.workspace }}/all/build
  BUILD_TYPE: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        platform: [ cl, gcc, clang ]
        build_type: [ Release ]

    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: |
          cmake -B $BUILD_OUTPUT_DIR -S $WORKSPACE
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DCMAKE_CXX_COMPILER=${{ matrix.platform == 'cl' && 'cl' || matrix.platform == 'gcc' && 'g++' || 'clang++' }}
          -DCMAKE_C_COMPILER=${{ matrix.platform }}
      - name: Build
        run: cmake --build $BUILD_OUTPUT_DIR --config $BUILD_TYPE
      - name: Test
        working-directory: $BUILD_OUTPUT_DIR
        run: ctest --build-config $BUILD_TYPE
